// Meet 的中文介面字串。邏輯在 core / home / poll，這裡只有文字與格式，
// 改這個檔不會改到行為。中英兩邊的鍵必須一致。
export const LANG = 'zh';

export const T = {
    signInFailed: '登入失敗：',
    addFailed: '加入失敗：',
    organizerRole: '發起人',
    participantRole: '參與者',
    yourReply: '我的回覆',
    notAnswered: '尚未回覆',
    copyPrompt: '複製這個網址：',
    orgPrefix: '發起人：',
    listSep: '、',
    gisLocale: 'zh_TW',
    fmtDay: (d) => `${String(d.getMonth() + 1).padStart(2, '0')}/${String(d.getDate()).padStart(2, '0')}`,
    timeLocale: 'zh-TW',
    rowMeta: (voters, slots) => `${voters} 人回覆 · ${slots} 個時段`,
    weekdays: ['日', '一', '二', '三', '四', '五', '六'],
    states: { yes: '可參加', notice: '需事先通知', no: '無法參加', pend: '尚未回覆' },
    loading: '載入中...',
    denied: '沒有權限讀這場會議。確認你登入的是收到邀請的那個 Google 帳號。',
    minutes: '分鐘',
    deadlineLabel: '截止',
    noDeadline: '無截止時間',
    repliedFmt: (n) => `已有 ${n} 人回覆`,   // 不給分母：分母只是「開過連結的人」，寫出來會讓人以為快收齊了
    titleRequired: '會議名稱不能空白',
    slotRequired: '至少要一個候選時段',
    quotaFull: (n) => `你同時進行中的會議已經有 ${n} 場，關掉一場再開新的。`,
    createFailed: '建立失敗：',
    voteFailed: '送出失敗：',
    closed: '已結束',
    open: '收票中',
    lockedBadge: '定案',
    bestBadge: '最多人可參加',
    proposedBy: (n) => `由 ${n} 提議`,
    youProposed: '由您提議',
    otherProposed: '由其他人提議',
    yesCount: (a, b) => `${a}/${b} 可參加`,
    answeredFmt: (a, b) => `您已回覆 ${a} / ${b} 個時段`,
    myYes: '您選擇「可參加」的時段：',
    nothingPicked: '尚未選擇',
    lockedNote: '發起人已定案，行事曆邀請將另行寄送。',
    verdictBest: '目前最多人可參加',
    verdictLocked: '已定案',
    lockBtn: '定案這個時段',
    unlockBtn: '取消定案',
    closeBtn: '刪除投票',
    deleteConfirm: '再按一次刪除',
    deleteFailed: '刪除失敗：',
    deleteBtn: '刪除',
    copyBtn: '網址',
    copyShare: '複製分享網址',
    codeEmpty: '先貼上時段碼。',
    codeOk: n => `帶入 ${n} 個時段。`,
    codeError: { format: '這串不是時段碼（要 MT1. 開頭）。', signature: '簽章不符，可能複製不完整或被改過。', payload: '內容解不開，請重新產生一次。', empty: '這串碼裡面沒有時段。' },
    noteSaved: '已儲存',
    noteFailed: '儲存失敗：',
    leadFmt: r => `目前預計 ${r}`,
    lockedFmt: r => `已定案 ${r}`,
    leadNone: '目前預計：還沒有人回覆',
    dupSlot: '此時段已存在，請選擇其他時間。',
    delSlot: '刪除這個時段',
    delSlotConfirm: '再按一次刪除',
    delSlotFailed: '刪除失敗：',
    removeVoter: '移除',
    removeConfirm: '再按一次',
    removeFailed: '移除失敗',
    repliedSlots: n => `已回 ${n} 個時段`,
    notRepliedYet: '尚未回覆',
    noVoters: '目前尚無人開啟此連結。',
    copyManual: '自動複製被瀏覽器擋住，請手動複製這個網址：',
    copied: '已複製',
    votingClosed: '這場會議已經結束收票。',
    lockedDone: '發起人已經定案，這場不再收票。',
    deadlinePassed: '已經過了投票截止時間。',
    confirmDelete: '刪除這場會議與所有回覆，確定？',
    noPolls: '尚未建立任何會議。',
    submitBtn: '送出',
    resubmitBtn: '更新我的回覆',
    submitting: '送出中…',
    pickSomething: '選擇完成後請按送出',
    unsaved: '有尚未送出的變更',
    submittedAt: (t) => `已於 ${t} 送出`,
    canEdit: '已送出。修改後可再次按下更新。',
    tallyFmt: (y, n, x) => `${y} 可參加 · ${n} 需事先通知 · ${x} 無法參加`,
    joinedNone: '尚未回覆任何會議。',
    nobody: '無',
    andMore: (n) => ` …共 ${n} 人`,
    totalPeople: '人',
    defaultPlace: 'Microsoft Teams',
    lengthHint: (n) => `建議時長 ${n} 分鐘`,
    homeDenied: '讀不到你的會議清單。Firebase 規則可能還沒發布。',
    guest: '訪客',
    guestNameRequired: '請先填你的名字，發起人才認得出是誰。',
    guestBadge: '訪客',
    notSignedIn: '（未登入）',
    nameSaved: '已更新',
    nameFailed: '更新失敗：',
    anonFailed: '匿名投票啟用失敗：',
    anonNeedsConsole: '匿名投票還沒啟用：Firebase Console → Authentication → Sign-in method → 匿名 → 啟用。',
    anonCannotCreate: '匿名身分僅能投票。建立會議請使用 Google 登入。'
};
