// Meet 的英文介面字串。邏輯在 core / home / poll，這裡只有文字與格式，
// 改這個檔不會改到行為。中英兩邊的鍵必須一致。
export const LANG = 'en';

export const T = {
    orgPrefix: 'by ',
    listSep: ', ',
    gisLocale: 'en',
    fmtDay: (d) => `${['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][d.getMonth()]} ${d.getDate()}`,
    timeLocale: 'en-GB',
    rowMeta: (voters, slots) => `${voters} replied · ${slots} times`,
    weekdays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    states: { yes: 'Available', notice: 'Needs notice', no: 'Unavailable', pend: 'No reply' },
    loading: 'Loading...',
    denied: 'No permission to read this meeting. Check that you signed in with the invited Google account.',
    minutes: 'min',
    deadlineLabel: 'Closes',
    noDeadline: 'No deadline',
    repliedFmt: (n) => `${n} replied so far`,   // No denominator: it would only count people who opened the link
    titleRequired: 'Meeting name is required',
    slotRequired: 'Add at least one candidate time',
    quotaFull: (n) => `You already have ${n} meetings running. Close one to start another.`,
    createFailed: 'Create failed: ',
    voteFailed: 'Submit failed: ',
    closed: 'Closed',
    open: 'Collecting',
    lockedBadge: 'Locked in',
    bestBadge: 'Most available',
    proposedBy: (n) => `proposed by ${n}`,
    youProposed: 'you proposed',
    otherProposed: 'proposed by a participant',
    yesCount: (a, b) => `${a}/${b} available`,
    answeredFmt: (a, b) => `You answered ${a} of ${b} times`,
    myYes: 'Marked as available: ',
    nothingPicked: 'none selected',
    lockedNote: 'The organizer locked this in. A calendar invite follows separately.',
    verdictBest: 'Currently most available',
    verdictLocked: 'Locked in',
    lockBtn: 'Lock this time',
    unlockBtn: 'Undo lock-in',
    closeBtn: 'Delete poll',
    deleteConfirm: 'Tap again to delete',
    deleteBtn: 'Delete',
    copyBtn: 'Link',
    copyShare: 'Copy share link',
    codeEmpty: 'Paste a slot code first.',
    codeOk: n => `${n} slot${n > 1 ? 's' : ''} filled in.`,
    codeError: { format: 'That is not a slot code (it must start with MT1.).', signature: 'Signature mismatch - the code may be incomplete or altered.', payload: 'The content could not be read. Generate the code again.', empty: 'This code carries no slots.' },
    noteSaved: 'Saved',
    noteFailed: 'Could not save: ',
    leadFmt: r => `Best so far ${r}`,
    lockedFmt: r => `Locked ${r}`,
    leadNone: 'Best so far: no replies yet',
    dupSlot: 'That slot is already on the list.',
    delSlot: 'Delete this slot',
    delSlotConfirm: 'Tap again to delete',
    delSlotFailed: 'Could not delete: ',
    removeVoter: 'Remove',
    removeConfirm: 'Tap again',
    removeFailed: 'Failed',
    repliedSlots: n => `${n} slot${n > 1 ? 's' : ''} answered`,
    notRepliedYet: 'No reply yet',
    noVoters: 'No one has opened this link yet.',
    copyManual: 'The browser blocked the automatic copy. Please copy this link manually:',
    copied: 'Copied',
    votingClosed: 'Voting is closed for this meeting.',
    lockedDone: 'The organizer locked a time; this poll no longer takes replies.',
    deadlinePassed: 'The voting deadline has passed.',
    confirmDelete: 'Delete this meeting and every reply. Are you sure?',
    noPolls: 'No meetings yet.',
    submitBtn: 'Submit',
    resubmitBtn: 'Update my reply',
    submitting: 'Submitting…',
    pickSomething: 'Pick your times, then hit Submit',
    unsaved: 'You have unsubmitted changes',
    submittedAt: (t) => `Submitted ${t}`,
    canEdit: 'Submitted. Change anything and hit update again.',
    tallyFmt: (y, n, x) => `${y} available · ${n} needs notice · ${x} unavailable`,
    joinedNone: 'You have not replied to any meeting yet.',
    nobody: 'nobody',
    andMore: (n) => ` …${n} in total`,
    totalPeople: 'people',
    yourReply: 'My reply',
    notAnswered: 'no reply yet',
    organizerRole: 'Organizer',
    participantRole: 'Participant',
    addFailed: 'Add failed: ',
    deleteFailed: 'Delete failed: ',
    signInFailed: 'Sign-in failed: ',
    copyPrompt: 'Copy this link:',
    defaultPlace: 'Microsoft Teams',
    lengthHint: (n) => `Suggested length: ${n} minutes`,
    homeDenied: "Can't read your meeting list. The Firebase rules may not be published yet.",
    guest: 'Guest',
    guestNameRequired: 'Please enter your name first so the organizer knows who replied.',
    guestBadge: 'Guest',
    notSignedIn: ' (not signed in)',
    nameSaved: 'Updated',
    nameFailed: 'Update failed: ',
    anonFailed: 'Anonymous voting failed: ',
    anonNeedsConsole: 'Anonymous voting is off: Firebase Console -> Authentication -> Sign-in method -> Anonymous -> Enable.',
    anonCannotCreate: 'Anonymous identities can vote only. Sign in with Google to create a meeting.'
};
